services:
  - type: web
    name: emotion-sentiment-app
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn app_optimized:app --host 0.0.0.0 --port $PORT --workers 1 --timeout 120
    plan: free
